//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyLanguage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp1.Resource.MyLanguage", typeof(MyLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 报警 的本地化字符串。
        /// </summary>
        internal static string AlmView {
            get {
                return ResourceManager.GetString("AlmView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴 的本地化字符串。
        /// </summary>
        internal static string AsixView {
            get {
                return ResourceManager.GetString("AsixView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紧凑面板宽度 的本地化字符串。
        /// </summary>
        internal static string CompactPaneLength {
            get {
                return ResourceManager.GetString("CompactPaneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示模式 的本地化字符串。
        /// </summary>
        internal static string DisplayMode {
            get {
                return ResourceManager.GetString("DisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单宽度/长度 的本地化字符串。
        /// </summary>
        internal static string Hamburger_Width___Height {
            get {
                return ResourceManager.GetString("Hamburger Width / Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单显示 的本地化字符串。
        /// </summary>
        internal static string HamburgerVisibility {
            get {
                return ResourceManager.GetString("HamburgerVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航页 的本地化字符串。
        /// </summary>
        internal static string IsPaneOpen {
            get {
                return ResourceManager.GetString("IsPaneOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲线 的本地化字符串。
        /// </summary>
        internal static string LiveChartView {
            get {
                return ResourceManager.GetString("LiveChartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        internal static string LogView {
            get {
                return ResourceManager.GetString("LogView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string MainWindowView {
            get {
                return ResourceManager.GetString("MainWindowView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动 的本地化字符串。
        /// </summary>
        internal static string MannualView {
            get {
                return ResourceManager.GetString("MannualView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监视 的本地化字符串。
        /// </summary>
        internal static string MonitoringView {
            get {
                return ResourceManager.GetString("MonitoringView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启面板宽度 的本地化字符串。
        /// </summary>
        internal static string OpenPaneLength {
            get {
                return ResourceManager.GetString("OpenPaneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配方参数 的本地化字符串。
        /// </summary>
        internal static string RecipeView {
            get {
                return ResourceManager.GetString("RecipeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面索引 的本地化字符串。
        /// </summary>
        internal static string SelectedIndex {
            get {
                return ResourceManager.GetString("SelectedIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口设置 的本地化字符串。
        /// </summary>
        internal static string Window_Seting {
            get {
                return ResourceManager.GetString("Window_Seting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口主题 的本地化字符串。
        /// </summary>
        internal static string Window_Thems {
            get {
                return ResourceManager.GetString("Window_Thems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口主题1 的本地化字符串。
        /// </summary>
        internal static string Window_Thems1 {
            get {
                return ResourceManager.GetString("Window_Thems1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口主题2 的本地化字符串。
        /// </summary>
        internal static string Window_Thems2 {
            get {
                return ResourceManager.GetString("Window_Thems2", resourceCulture);
            }
        }
    }
}
